### ISSUE TITLE
Demo Example 6: decimal places - Wrong decimal_factor value

### ISSUE THREAD

**Issue by Saren-Arterius** [aishek/jquery-animateNumber#10]
var decimal_factor = decimal_places === 0 ? 1 : decimal_places * 10;

should be

    var decimal_factor = decimal_places === 0 ? 1 : Math.pow(10, decimal_places);

**Comment by aishek** [comment]
[Fixed](http://aishek.github.io/jquery-animateNumber/#example-6), thanks!
