### ISSUE TITLE
release new tag to support bower 

### ISSUE THREAD

**Issue by okendoken** [aishek/jquery-animateNumber#11]
Great package, thanks!

Currently when installed via bower the package is being fetch without bower.json file. Please release a new tag with bower.json included.

Check the tree at 0.0.10 state - it has no bower.json https://github.com/aishek/jquery-animateNumber/tree/v0.0.10

Thanks!

**Comment by aishek** [comment]
I've released new tag with `bower.json` included. Also [added jquery-animateNumber to npm registry](https://www.npmjs.com/package/jquery.animate-number).

@okendoken everything is fine now?

**Comment by okendoken** [comment]
@aishek yep, all is good. Thank you!
