### ISSUE TITLE
Передать значение number из html

### ISSUE THREAD

**Issue by evgenyshev** [aishek/jquery-animateNumber#14]
Хороший скрипт, но очень неудобно задавать значения в скрипте. Хотелось бы иметь возможность передать значение для параметра "number" из самого элемента. 
Пробовал так:
```javascript
var number_value = $(this).data('numval');
$('.numberanimate').animateNumber({
number: number_value
}, 500);
```
```
<span id="valuebriks" class="numberanimate" data-numval="700">0</span>
```
но не получаеться. Видимо, скрипт не понимает, что this — это об этом элементе. Или я что-то делаю не так?

**Comment by aishek** [comment]
Что-то явно не так. Можете весь скрипт целиком показать?

**Comment by evgenyshev** [comment]
Это весь скрипт)

**Comment by aishek** [comment]
Вижу же, что нет :) А пришлите ссылку на codepen какой-нибудь?

**Comment by aishek** [comment]
Я так понимаю, что проблема решена-таки :)
