### ISSUE TITLE
Updating on the go to create a "live" counter

### ISSUE THREAD

**Issue by Coriou** [aishek/jquery-animateNumber#15]
I'm trying to make it so that I could update the number given to animateNumber every X seconds (the data would be coming from an ajax request) without restarting the counter from 0. Is this possible ?

**Comment by aishek** [comment]
Yes, it is. Use `prop('number', x)` to keep value.

**Comment by Coriou** [comment]
Stupid me. Just after filling the issue I read that in the example. Just a side question if you may, before I close this : have you ever had a problem running animateNumber on multiple elements at the same time ?

**Comment by Coriou** [comment]
Know what ? I finished typing this, went back to my code and noticed a huge mistake I made. Now, it's all good of course ... Well, let not this issue be totally useless : thank you for the awesome plugin ! =)

**Comment by aishek** [comment]
I'm glad you've got it working =)
It is one of the most simplest things I've ever create. Just wondering about its popularity.
