### ISSUE TITLE
Uncaught TypeError: $(...).animateNumber is not a function

### ISSUE THREAD

**Issue by aweibel** [aishek/jquery-animateNumber#16]
I get `Uncaught TypeError: $(...).animateNumber is not a function` on your demo page. It used to work just fine. The implementation I've used stopped working with the same error as well.

**Comment by aweibel** [comment]
Looks like it was a chrome browser plugin that was inserting JS on web pages I visited that broke your JS. Please close this ticket. I apologize.

**Comment by aishek** [comment]
That's ok. 👍
