### ISSUE TITLE
Google Chrome browser crashes on text highlighting

### ISSUE THREAD

**Issue by webgodo** [aishek/jquery-animateNumber#18]
Hi. Thanks for your nice plugin. It has a problem in `Google Chrome`. When it is counting numbers up/down, if you **select (highlight) text** via mouse, the page crashes completely.

**Comment by aishek** [comment]
I've tested at 50.0.2661.86 (64-bit) [Example 3](http://aishek.github.io/jquery-animateNumber/#example-3) ant it works.

Could you provide an example page to demonstrate the error?
