### ISSUE TITLE
numberStepFactories.separator returns NaN for negative numbers with three digits

### ISSUE THREAD

**Issue by ncote** [aishek/jquery-animateNumber#19]
The default numberStepFactories.separator (i.e. with three-digit groupings) shows NaN for negative numbers having exactly three digits (or rather multiples of three digits).

Example: 
```
$('#world-population').animateNumber( {
      number: -222,
      numberStep: $.animateNumber.numberStepFactories.separator(',')
      });
```
This will show "NaN,222" , presumably because the negative sign is left in a digit group by itself.

**Comment by aishek** [comment]
Just published [`v0.0.14`](https://github.com/aishek/jquery-animateNumber/releases/tag/v0.0.14) with fixes for the issue.

@ncote kudos for reporting!
