### ISSUE TITLE
Unable to use HTML for number separator

### ISSUE THREAD

**Issue by Devportobello** [aishek/jquery-animateNumber#21]
Unable to use html for number separator eg:
```javascript
var comma_separator_number_step = $.animateNumber.numberStepFactories.separator('&nbsp;');
$this.animateNumber({number: 100,numberStep: comma_separator_number_step},2000 });
```
Library use jquery ```.text()``` to [concatenate separator](https://github.com/aishek/jquery-animateNumber/blob/master/jquery.animateNumber.js#L134), is there possibility to [add another settings](https://github.com/aishek/jquery-animateNumber/blob/master/jquery.animateNumber.js#L142) to choose between ```.text()``` or ```.html()``` ?

**Comment by aishek** [comment]
What if replace `&nbsp;` with whitespace character itself? Should work.

**Comment by Devportobello** [comment]
whitespace and ```&nbsp;``` are not same effect, the last stop the browser from breaking a line in the wrong place.

**Comment by aishek** [comment]
I mean you should try to use non-breakable space as UTF-8 symbol, not as HTML mnemonic. It should work as you expect.

**Comment by Devportobello** [comment]
👍 Work with UTF-8 symbol, thx.

**Comment by aishek** [comment]
🍺
