### ISSUE TITLE
Add support to animate "value" inside of <input> tag

### ISSUE THREAD

**Issue by vzlatkin** [aishek/jquery-animateNumber#23]
The current version of the code uses $el.text() to set the value during animation, but that doesn't work with <input> tags.

I made changes like the below to get it to work:

`
            if (d(a.elem).prop("tagName") === "INPUT") {
                d(a.elem).prop("value",e);
            } else {
                d(a.elem).text(e);
            }
`

**Comment by aishek** [comment]
Current version have such ability. Why just not override `numberStep` function like so:

```
$('#fun-level').animateNumber(
  {
    numberStep: function(now, tween) {
      var floored_number = Math.floor(now),
      target = $(tween.elem);

      target.prop("value", floored_number);
    }
  },
  1800
);
```
