### ISSUE TITLE
Custom animation start point with decimal doesn't works ?

### ISSUE THREAD

**Issue by robinb78** [aishek/jquery-animateNumber#25]
Hi !

Thanks for that awesome plugin !

Is there a problem when we mix "custom animation start point" and "decimal places" ?

That seems to doesn't work and always start to 0.

Exemple : 

`var decimal_places = 2;
        var decimal_factor = decimal_places === 0 ? 1 : Math.pow(10, decimal_places);
        
        selector
        .prop('number', 22.55)
        .animateNumber(
          {
            number: 40.32* decimal_factor,
            numberStep: function(now, tween) {
                var floored_number = Math.floor(now) / decimal_factor,
                    target = $(tween.elem);
                    
                    
                    if (decimal_places > 0) {
                      
                    // force decimal places even if they are 0
                      floored_number = floored_number.toFixed(decimal_places);

                      // replace '.' separator with ','
                      floored_number = floored_number.toString().replace('.', ',');
                    }
                
                    target.text(floored_number);
                
              }
          },
          500
        );`

Have you any idea ?

Thanks a lot.
Robin

**Comment by aishek** [comment]
G'day, Robin. Thanks for kind words.

I think the problem is in `prop` call, there is missing multiplication. All you need is something like:
```js
  var decimal_places = 2;
  var decimal_factor = decimal_places === 0 ? 1 : Math.pow(10, decimal_places);

  $('#target')
    .prop('number', 22.55 * decimal_factor)
    .animateNumber(
    {
      number: 40.32 * decimal_factor,
      numberStep: function(now, tween) {
        var floored_number = Math.floor(now) / decimal_factor;

        $(tween.elem).text(floored_number);
      }
    },
    500
  );
```

**Comment by robinb78** [comment]
That's works !

Thanks a lot you're great.

Have a good day from France
