### ISSUE TITLE
broken in latest version of Jquery 3.x

### ISSUE THREAD

**Issue by acbrandao** [aishek/jquery-animateNumber#30]
Yes, i see its only compatible with a select versions  of older JQuery , any chance you can update it to work with the most recent ones 3.x. Mainly because I try to use it on page(s) that just point to the latest CDN versions of Jquery and I would like to **really** use your script with them. Thanks

**Comment by aishek** [comment]
G'day Tony, I've just checked jQuery `3.3.1` version and the plugin works. Did you get other results? Which version? Could you provide some sort of codepen link?
