### ISSUE TITLE
easings don't seem to work when defined as an option

### ISSUE THREAD

**Issue by mastef** [aishek/jquery-animateNumber#31]
I've tried now multiple approaches to get easings to work. Been trying different jquery versions, etc. - the only way for me to make it work is to define the easing as an extra parameter. When an easing is defined as an option, it seems to be ignored.

So this approach ( as defined in the readme ) doesn't seem to work :

```js
$(el).animateNumber(
    {
        number: 123,
        easing: 'easeInOutBack' // <-- doesn't seem to work
    },
    5000,
    function() {
        // some callback
    }
);
```

But this one does : 

```js
$(el).animateNumber(
    {
        number: 123
    },
    5000,
    'easeInOutBack',  // <-- works
    function() {
        // some callback
    }
);
```

**Comment by mastef** [comment]
@aishek that was what was confusing me too in the start, but actually the demo does not show an easing effect based on the parameter. This parameter is not working in the demo.

Simple test : Replace it with `easeInOutBack` and the number should go down first to -10, then up to 110, and finally to 100.

Will not work ( current demo code ) : 
```js
          $('#fun-level-run').off('click');
          $('#fun-level-run').click(function(){
            var percent_number_step = $.animateNumber.numberStepFactories.append(' %')
            $('#fun-level').animateNumber(
              {
                number: 100,
                color: 'green',
                'font-size': '30px',
                easing: 'easeInOutBack',
                numberStep: percent_number_step
              },
              15000
            );
            return false;
          });
```
Will work : 
```js
          $('#fun-level-run').off('click');
          $('#fun-level-run').click(function(){
            var percent_number_step = $.animateNumber.numberStepFactories.append(' %')
            $('#fun-level').animateNumber(
              {
                number: 100,
                color: 'green',
                'font-size': '30px',
                numberStep: percent_number_step
              },
              15000, 'easeInOutBack'
            );
            return false;
          });
```

**Comment by mastef** [comment]
I found the issue. According to the [jquery animate documentation](http://api.jquery.com/animate/) the first object is for css properties, the second object is for options. 

So in fact it has to be something like this : 

```js
          $('#fun-level-run').off('click');
          $('#fun-level-run').click(function(){
            var percent_number_step = $.animateNumber.numberStepFactories.append(' %')
            $('#fun-level').animateNumber(
              {
                number: 100,
                color: 'green',
                'font-size': '30px',
                numberStep: percent_number_step
              },
              {
                easing: 'easeInOutBack',
                duration: 15000
              }
            );
            return false;
          });
```

Which is a bit confusing, but meh. I guess worth updating your docs with the working version.

**Comment by aishek** [comment]
It's funny I was unable to read my own code correctly :-)

If you could make pull request with the fix it will be great

**Comment by aishek** [comment]
I've updated readme and the demo.

@mastef Thanks for the contribute!
