### ISSUE TITLE
Ressetting to 0 - looping animations

### ISSUE THREAD

**Issue by isaydesign** [aishek/jquery-animateNumber#32]
Hello, I have a series of numbers that animate after each other.

When I get to the last number, i'd like to animate the first number again, but when I call the function again the number stays at it's max value.

How can I reset the animation?
Thanks in advance.

**Comment by aishek** [comment]
Could you provide an example via codepen or something similar?

**Comment by isaydesign** [comment]
Hello, I managed to do it, so this can be closed.
