### ISSUE TITLE
Callback when animation ends

### ISSUE THREAD

**Issue by be-codified** [aishek/jquery-animateNumber#6]
Hi,

thank you for the great plugin.

Is there an option for callback when counter reach its end value (or when the animation stops)? Thank you again.

**Comment by aishek** [comment]
Yes, there is: I've added [example of animation end callback usage](http://aishek.github.io/jquery-animateNumber/#example-8).

It uses [jQuery animation API](http://api.jquery.com/animate/), so check it out also.

**Comment by be-codified** [comment]
Hi Alexandr, thank you for the given example, I appreciate it.
