### ISSUE TITLE
using jquery-animate-numbers with input ?

### ISSUE THREAD

**Issue by YouSour** [aishek/jquery-animateNumber#7]
i just using jquery-animate-numbers , i don't how to use with input , any idea ?

**Comment by aishek** [comment]
Can't understand. Could you give some code example maybe?

**Comment by YouSour** [comment]
<input type="number" id="money" value="0"/>
<button type="button" id="btnAdd">add</button>
If i click on button #btnAdd value input change with animation ! 
Any idea ???

**Comment by aishek** [comment]
```js
$('#money').animateNumber(
  {
    number: 72,
    numberStep: function(now, tween) {
      var target = $(tween.elem);

      target
        .prop('number', now) // keep current prop value
        .val(now);
    },
    'slow'
  }
);
```

**Comment by YouSour** [comment]
thank you for info ! :+1:

**Comment by aishek** [comment]
:sunglasses:
