### ISSUE TITLE
animateNumber on toggle

### ISSUE THREAD

**Issue by c0sm1n87** [aishek/jquery-animateNumber#9]
Hello,

Was wondering if I could create a scenario where using your plugin and a checkbox. 

based on smth (really crude / basic)

		$(selector).change(function(){
			if (this.checked) {
				animateNumber to 11111
			} else {
				animateNumber to 111
			}
		});

Basically to count up upon checking and count down upon unchecking.

**Comment by aishek** [comment]
@c0sm1n87 see http://aishek.github.io/jquery-animateNumber/#example-9

**Comment by c0sm1n87** [comment]
@aishek thanks for the solution, really helpful!
